"""Regenerate the offline starter-label document using the existing worker qrcode dependency.

Usage: worker\\.venv\\Scripts\\python.exe scripts\\generate-beta-labels.py
The output is intentional user-facing vector documentation, not inventory data.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import xml.etree.ElementTree as ET

import qrcode
from qrcode.image.svg import SvgPathImage


def label_svg(value: str) -> str:
    qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M, box_size=10, border=4)
    qr.add_data(value)
    qr.make(fit=True)
    svg = ET.fromstring(qr.make_image(image_factory=SvgPathImage).to_string())
    ET.register_namespace("", "http://www.w3.org/2000/svg")
    svg.set("role", "img")
    svg.set("aria-label", f"QR code {value}")
    for element in svg.iter():
        if "id" in element.attrib:
            element.set("id", f"{value}-{element.get('id')}")
    return ET.tostring(svg, encoding="unicode")


def build_html() -> str:
    cards = []
    for number in range(1, 11):
        sku = f"{number:06d}"
        value = f"BC-{sku}"
        cards.append(f'''<article class="label" data-payload="{value}">
{label_svg(value)}
<div><p class="brand">BLACK CAT · STARTER LABEL</p><h2>{sku}</h2><p class="payload">{value}</p><p class="reminder">Photograph this marker<br>LAST for this garment.</p></div>
</article>''')
    return '''<!doctype html>
<!-- Generated by scripts/generate-beta-labels.py. Self-contained vector labels; no inventory records. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Black Cat — ten starter SKU labels</title>
<style>
* { box-sizing: border-box; }
body { font-family: Arial, sans-serif; color: #111; background: #fff; margin: 20px auto; padding: 0 12px; max-width: 190mm; }
h1 { font-size: 22px; margin: 0 0 8px; }
header p { font-size: 13px; line-height: 1.4; margin: 6px 0; }
.screen { margin-bottom: 16px; font-size: 14px; line-height: 1.5; }
a { color: #163d82; }
a:focus-visible { outline: 2px solid #163d82; outline-offset: 3px; }
.labels { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 2mm; margin-top: 4mm; }
.label { display: grid; grid-template-columns: 33mm minmax(0, 1fr); align-items: center; gap: 2mm; border: .25mm dashed #777; padding: 2mm; min-height: 38mm; break-inside: avoid; background: white; }
.label svg { display: block; width: 33mm; height: 33mm; background: white; }
.label h2 { font-size: 23px; margin: 3px 0; letter-spacing: 1px; }
.brand { font-size: 7px; margin: 0; font-weight: bold; }
.payload { font: 11px monospace; margin: 3px 0; }
.reminder { font-size: 9px; line-height: 1.3; margin: 5px 0 0; }
footer { font-size: 10px; margin: 3mm 0 0; line-height: 1.4; }
@media screen and (max-width: 600px) { .labels { grid-template-columns: 1fr; } }
@page { margin: 10mm; }
@media print {
  body { margin: 0; padding: 0; max-width: none; }
  .screen { display: none; }
  h1 { font-size: 16px; margin-bottom: 4px; }
  header p { font-size: 10px; line-height: 1.3; margin: 4px 0; }
  .labels { grid-template-columns: repeat(2, minmax(0, 1fr)); }
}
</style></head><body>
<nav class="screen"><a href="/setup">Back to Getting started</a> · When opened as a downloaded file, return through Settings → Getting started in the desktop app.</nav>
<header><h1>Ten starter SKU labels</h1>
<p><strong>Use only with a NEW empty inventory or after confirming that SKUs 000001–000010 are all unused.</strong> These labels create real inventory numbers when photographed and imported. Use different labels for existing SKUs.</p>
<p>Take at least three garment photos, then photograph its matching marker as a separate LAST image. Repeat for each garment. Keep the marker sharp, upright and free from glare.</p>
<p class="screen">Print from your browser with <strong>Ctrl+P</strong>. Use plain white paper, 100% scale, and turn off browser headers/footers. Cut around the dashed lines, keeping the white QR border. This file works offline and needs no sign-in.</p></header>
<main class="labels" aria-label="Ten printable SKU labels">
''' + "\n".join(cards) + '''
</main><footer>QR payloads are BC-000001–BC-000010; default inventory SKUs normalize to 000001–000010. Match any customized SKU settings. Keep the white border around each QR code when cutting.</footer>
</body></html>
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1] / "public" / "beta-labels.html")
    output = parser.parse_args().output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_html(), encoding="utf-8", newline="\n")
    print("Generated ten printable starter SKU labels.")


if __name__ == "__main__":
    main()
