// config/template.db is what electron/main.js copies to create a user's database
// on first run, so a stale copy hands the app a schema its own queries do not
// match — every read of a newer column then fails with Prisma P2022. It drifted
// exactly that way once: the local template predated Item.shippingCharged, so a
// from-source first run could not read earnings at all.
//
// The file is gitignored and regenerated by `npm run db:template` (which `npm run
// pack` runs before building, so releases carry a fresh one). That means it is a
// LOCAL artifact that silently rots whenever the schema changes and nobody
// regenerates it. This catches that before it reaches a database.
//
// Absent is fine — a fresh clone has not generated it yet, and there is nothing
// to validate. Present-and-stale is the failure worth reporting.
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { DatabaseSync } from "node:sqlite";
import { assertEmptyTemplate } from './build-template.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const templatePath = path.join(root, "config", "template.db");
const schemaPath = path.join(root, "prisma", "schema.prisma");

/** Field names of one `model X { ... }` block, skipping comments, block
 *  attributes (@@index) and relation fields (which have no column). */
function schemaFields(schema, model) {
  // String.raw: a plain template literal would swallow the regex backslashes.
  const block = new RegExp(
    String.raw`model\s+${model}\s*\{([\s\S]*?)\n\}`).exec(schema);
  assert.ok(block, `model ${model} not found in schema.prisma`);
  const fields = [];
  for (const raw of block[1].split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("//") || line.startsWith("@@")) continue;
    const match = /^(\w+)\s+(\w+)(\[\])?/.exec(line);
    if (!match) continue;
    const [, name, type, list] = match;
    // A list field, or a field whose type is another model, is a relation and
    // has no column of its own on this table.
    if (list) continue;
    if (/^[A-Z]/.test(type) &&
        new RegExp(String.raw`model\s+${type}\s*\{`).test(schema)) continue;
    fields.push(name);
  }
  return fields;
}

test("config/template.db carries every column the Prisma schema declares", (t) => {
  if (!fs.existsSync(templatePath)) {
    return t.skip("config/template.db not generated yet — `npm run db:template` creates it");
  }
  // Normalize CRLF: the model-block regex anchors on a bare newline.
  const schema = fs.readFileSync(schemaPath, "utf-8").split("\r\n").join("\n");
  const db = new DatabaseSync(templatePath, { readOnly: true });
  try {
    for (const model of ["Item", "Photo", "Batch", "AppSettings"]) {
      const columns = new Set(
        db.prepare(`PRAGMA table_info(${model})`).all().map((r) => r.name));
      const missing = schemaFields(schema, model).filter((f) => !columns.has(f));
      assert.deepEqual(missing, [],
        `config/template.db is stale: ${model} is missing ${missing.join(", ")}. ` +
        "Run `npm run db:template` to regenerate it — a stale template gives a " +
        "first-run database the app's own queries cannot read.");
    }
  } finally {
    db.close();
  }
});

test("config/template.db ships empty — it is a schema seed, not data", (t) => {
  if (!fs.existsSync(templatePath)) {
    return t.skip("config/template.db not generated yet — `npm run db:template` creates it");
  }
  const db = new DatabaseSync(templatePath, { readOnly: true });
  try {
    for (const table of ["Item", "Photo", "Batch"]) {
      const { n } = db.prepare(`select count(*) as n from ${table}`).get();
      assert.equal(n, 0, `template.db must not ship rows in ${table}`);
    }
    for (const { name } of db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").all()) {
      const quoted = '"' + name.replaceAll('"', '""') + '"';
      assert.equal(db.prepare(`SELECT COUNT(*) AS n FROM ${quoted}`).get().n, 0, `template.db must not ship rows in ${name}`);
    }
  } finally {
    db.close();
  }
});

test('the template carries every declared model and scalar field and no private table data', t => {
  if (!fs.existsSync(templatePath)) return t.skip('config/template.db not generated yet');
  assertEmptyTemplate(templatePath, { schemaText: fs.readFileSync(schemaPath, 'utf8') });
});

// The runtime migrator (scripts/schema-sync.mjs) trusts config/schema-manifest.json to
// describe the shipped schema. A stale manifest is worse than none: it would let an
// upgraded tester keep a database that is missing exactly the columns the new build
// needs, and report success. Both files are regenerated together by `npm run db:template`,
// and this is the guard that says so when they drift.
test("config/schema-manifest.json matches config/template.db", async (t) => {
  const manifestPath = path.join(root, "config", "schema-manifest.json");
  if (!fs.existsSync(templatePath)) return t.skip("config/template.db not generated yet");
  if (!fs.existsSync(manifestPath)) {
    assert.fail("config/schema-manifest.json is missing — run `npm run db:template` to generate it");
  }
  const { readSchema } = await import("./schema-manifest.mjs");
  const live = readSchema(templatePath);
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  const tablesNow = Object.keys(live.tables).sort();
  const tablesManifest = Object.keys(manifest.tables ?? {}).sort();
  assert.deepEqual(tablesManifest, tablesNow,
    "schema-manifest.json is stale (table list differs) — run `npm run db:template`");
  for (const table of tablesNow) {
    const now = live.tables[table].columns.map((c) => `${c.name}:${c.type}:${c.notnull ? 1 : 0}:${c.dflt ?? ""}`);
    const was = (manifest.tables[table]?.columns ?? []).map((c) => `${c.name}:${c.type}:${c.notnull ? 1 : 0}:${c.dflt ?? ""}`);
    assert.deepEqual(was, now,
      `schema-manifest.json is stale for ${table} — run \`npm run db:template\``);
  }
  assert.equal((manifest.indexes ?? []).length, live.indexes.length,
    "schema-manifest.json is stale (index count differs) — run `npm run db:template`");
});
